name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm ci
      - uses: stefanoeb/eslint-action@1.0.2
        with:
          files: src/
